ci: store package and ffmpeg versions as job artifacts
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

diff --git a/solutions/cdn/demo-setup b/solutions/cdn/demo-setup
--- a/solutions/cdn/demo-setup
+++ b/solutions/cdn/demo-setup
@@ -23,9 +23,9 @@
 video_grps=($(ls -g /dev/dri/renderD* | awk '{print $3}' | uniq))
 
 if [ ${#video_grps[@]} -eq 0 ]; then
-  echo "error: no render node GPU devices exposed"
-  echo "error:   if you run under docker you might need to map devices"
-  echo "error:   with commands like --device=/dev/dri or --privileged"
+  echo "error: no render node GPU devices exposed" >&2
+  echo "error:   if you run under docker you might need to map devices" >&2
+  echo "error:   with commands like --device=/dev/dri or --privileged" >&2
   exit -1
 fi
 
@@ -35,7 +35,7 @@ function add_users_to_group()
   shift
   for usr in $@; do
     if ! sudo usermod -aG $grp $usr; then
-      echo "error: failed to add user to '$grp' group: $usr"
+      echo "error: failed to add user to '$grp' group: $usr" >&2
       exit -1
     fi
   done
@@ -51,7 +51,7 @@ for grp in ${video_grps[@]}; do
     # create the group.
     grpname=mds_render$n
     if ! sudo groupadd -g $grp $grpname; then
-      echo "error: failed to create '$grpname' corresponding to GID: $grp"
+      echo "error: failed to create '$grpname' corresponding to GID: $grp" >&2
       exit -1
     fi
     n=$((++n))
