bench/quality: include additional bats tests
Fixes: #27

Signed-off-by: Daniel Socek <daniel.socek@intel.com>

diff --git a/benchmark/quality/bench-quality b/benchmark/quality/bench-quality
--- a/benchmark/quality/bench-quality
+++ b/benchmark/quality/bench-quality
@@ -342,18 +342,18 @@ function get_bitrates() {
     elif [ "$resolution" = "SD" ]; then
       echo "1 1.5 3 6 12"
     else
-      echo "bug: invalid resolution: $res" >&2
+      echo "bug: invalid resolution: $resolution" >&2
       exit -1
     fi
   elif [ "$codec" = "HEVC" ]; then
-    if [ "$res" = "4K" ]; then
+    if [ "$resolution" = "4K" ]; then
       echo "6 9 15 24 40"
-    elif [ "$res" = "HD" ]; then
+    elif [ "$resolution" = "HD" ]; then
       echo "2 3 6 9 15"
-    elif [ "$res" = "SD" ]; then
+    elif [ "$resolution" = "SD" ]; then
       echo "1 1.5 3 4.5 7.5"
     else
-      echo "bug: invalid resolution: $res" >&2
+      echo "bug: invalid resolution: $resolution" >&2
       exit -1
     fi
   else
@@ -380,7 +380,7 @@ function get_coding_commandline_options() {
     options_ref="-preset veryslow -profile:v high"
   elif [ "$codec" = "HEVC" ]; then
     if [ "$preset" = "best" ]; then
-      options_qsv="-extbrc 1 -qmin 1 -qmax 51 -refs 5"
+      options_qsv="-extbrc 1 -bf 7 -refs 5"
       options_senc="-extbrc:on -x 5"
     elif [[ ! $preset =~ default ]]; then
       echo "error: invalid encoding options preset (default, best): $preset" >&2
