bench/quality: fix predef streams
Signed-off-by: Daniel Socek <daniel.socek@intel.com>

diff --git a/benchmark/quality/bench-quality b/benchmark/quality/bench-quality
--- a/benchmark/quality/bench-quality
+++ b/benchmark/quality/bench-quality
@@ -262,9 +262,8 @@ function run() {
   local prefix=$2
   local width=$3
   local height=$4
-  local nframes=$5
-  local framerate=$6
-
+  local framerate=$5
+  local nframes=$6
   local _exit=no
   if [ -d $file ]; then
     stream=$(find_stream $file $stream)
@@ -627,6 +626,54 @@ function compute_bdrate_averages() {
   fi
 }
 
+function get_preset_stream() {
+  local ind=$1
+  if   [[ $ind = 1  ]]; then echo "BoatNF_1280x720_60.yuv" "Boat_720p" 1280 720 60 300
+  elif [[ $ind = 2  ]]; then echo "crowd_run_1280x720_50.yuv" "CrowdRun_720p" 1280 720 50 500
+  elif [[ $ind = 3  ]]; then echo "Kimono1_1280x720_24.yuv" "Kimono_720p" 1280 720 24 240
+  elif [[ $ind = 4  ]]; then echo "FoodMarket2NF_1280x720_60.yuv" "FoodMarket2_720p" 1280 720 60 300
+  elif [[ $ind = 5  ]]; then echo "PierSeasideNF_1280x720_60.yuv" "PierSeaside_720p" 1280 720 60 600
+  elif [[ $ind = 6  ]]; then echo "TangoNF_1280x720_60.yuv" "Tango_720p" 1280 720 60 294
+  elif [[ $ind = 7  ]]; then echo "park_joy_1280x720_50.yuv" "ParkJoy_720p" 1280 720 50 500
+  elif [[ $ind = 8  ]]; then echo "ParkScene_1280x720_24.yuv" "ParkScene_720p" 1280 720 24 240
+  elif [[ $ind = 9  ]]; then echo "touchdown_pass_1280x720_30.yuv" "TouchdownPass_720p" 1280 720 30 570
+  elif [[ $ind = 10 ]]; then echo "BasketballDrive_1920x1080_50.yuv" "BasketballDrive_1080p" 1920 1080 50 500
+  elif [[ $ind = 11 ]]; then echo "bq_terrace_1920x1080p_600_60.yuv" "BQTerrace_1080p" 1920 1080 60 600
+  elif [[ $ind = 12 ]]; then echo "Cactus_1920x1080_50.yuv" "Cactus_1080p" 1920 1080 50 500
+  elif [[ $ind = 13 ]]; then echo "crowd_run_1920x1080p_500_50.yuv" "CrowdRun_1080p" 1920 1080 60 600
+  elif [[ $ind = 14 ]]; then echo "DinnerScene_1920x1080_60.yuv" "DinnerScene_1080p" 1920 1080 60 600
+  elif [[ $ind = 15 ]]; then echo "park_joy_1920x1080_500_50.yuv" "ParkJoy_1080p" 1920 1080 50 500
+  elif [[ $ind = 16 ]]; then echo "Kimono1_1920x1080_24.yuv" "Kimono_1080p" 1920 1080 24 240
+  elif [[ $ind = 17 ]]; then echo "RedKayak_1920x1080_30.yuv" "RedKayak_1080p" 1920 1080 30 570
+  elif [[ $ind = 18 ]]; then echo "RushFieldCuts_1920x1080_30.yuv" "RushFieldCuts_1080p" 1920 1080 30 570
+  elif [[ $ind = 19 ]]; then echo "Bunny_1920x1080_24_600.yuv" "Bunny_1080p" 1920 1080 24 600
+  elif [[ $ind = 20 ]]; then echo "CSGO_1920x1080_60.yuv" "CSGO_1080p" 1920 1080 60 600
+  elif [[ $ind = 21 ]]; then echo "DOTA2_1920x1080_60_600.yuv" "DOTA2_1080p" 1920 1080 60 600
+  elif [[ $ind = 22 ]]; then echo "GTAV_1920x1080_60_600.yuv" "GTAV_1080p" 1920 1080 60 600
+  elif [[ $ind = 23 ]]; then echo "Hearthstone_1920x1080_60.yuv" "Hearthstone_1080p" 1920 1080 60 600
+  elif [[ $ind = 24 ]]; then echo "MINECRAFT_1920x1080_60_600.yuv" "MINECRAFT_1080p" 1920 1080 600 60
+  elif [[ $ind = 25 ]]; then echo "MrFox_BlueBird_1920x1080_30.yuv" "MrFox_BlueBird_1080p" 1920 1080 30 300
+  elif [[ $ind = 26 ]]; then echo "Sintel_trailer_o537n480_1920x1080_24.yuv" "Sintel_trailer_1080p" 1920 1080 24 480
+  elif [[ $ind = 27 ]]; then echo "WITCHER3_1920x1080_60.yuv" "WITCHER3_1080p" 1920 1080 60 600
+  else
+    echo "error: invalid preset stream index: $ind" >&2
+    exit -1
+  fi
+}
+
+function is_preset_stream() {
+  local file=$1
+  local stream=""
+  for i in {1..27}; do
+    stream=$(get_preset_stream $i | cut -d " " -f1)
+    if [[ $stream = $file ]]; then
+      echo "yes"
+      return
+    fi
+  done
+  echo "no"
+}
+
 err=0
 is_yuv=no
 file=$(realpath $1)
@@ -640,39 +687,17 @@ if [[ ! -d "$file" ]]; then
   fi
 fi
 
-if [[ -d "$file" || "$is_yuv" = "yes" && "$(can_process_yuv $width $height $framerate)" = "no" ]]; then
-  # 720p SD streams...
-  run "BoatNF_1280x720_60.yuv" "Boat_720p" 1280 720 300 60
-  run "crowd_run_1280x720_50.yuv" "CrowdRun_720p" 1280 720 500 50
-  run "Kimono1_1280x720_24.yuv" "Kimono_720p" 1280 720 240 24
-  run "FoodMarket2NF_1280x720_60.yuv" "FoodMarket2_720p" 1280 720 300 60
-  run "PierSeasideNF_1280x720_60.yuv" "PierSeaside_720p" 1280 720 600 60
-  run "TangoNF_1280x720_60.yuv" "Tango_720p" 1280 720 294 60
-  run "park_joy_1280x720_50.yuv" "ParkJoy_720p" 1280 720 500 50
-  run "ParkScene_1280x720_24.yuv" "ParkScene_720p" 1280 720 240 24
-  run "touchdown_pass_1280x720_30.yuv" "TouchdownPass_720p" 1280 720 570 30
-
-  # 1080p HD streams...
-  run "BasketballDrive_1920x1080_50.yuv" "BasketballDrive_1080p" 1920 1080 500 50
-  run "bq_terrace_1920x1080p_600_60.yuv" "BQTerrace_1080p" 1920 1080 600 60
-  run "Cactus_1920x1080_50.yuv" "Cactus_1080p" 1920 1080 500 50
-  run "crowd_run_1920x1080p_500_50.yuv" "CrowdRun_1080p" 1920 1080 600 60
-  run "DinnerScene_1920x1080_60.yuv" "DinnerScene_1080p" 1920 1080 600 60
-  run "park_joy_1920x1080_500_50.yuv" "ParkJoy_1080p" 1920 1080 500 50
-  run "Kimono1_1920x1080_24.yuv" "Kimono_1080p" 1920 1080 240 24
-  run "RedKayak_1920x1080_30.yuv" "RedKayak_1080p" 1920 1080 570 30
-  run "RushFieldCuts_1920x1080_30.yuv" "RushFieldCuts_1080p" 1920 1080 570 30
-  run "Bunny_1920x1080_24_600.yuv" "Bunny_1080p" 1920 1080 600 24
-  run "CSGO_1920x1080_60.yuv" "CSGO_1080p" 1920 1080 600 60
-  run "DOTA2_1920x1080_60_600.yuv" "DOTA2_1080p" 1920 1080 600 60
-  run "GTAV_1920x1080_60_600.yuv" "GTAV_1080p" 1920 1080 600 60
-  run "Hearthstone_1920x1080_60.yuv" "Hearthstone_1080p" 1920 1080 600 60
-  run "MINECRAFT_1920x1080_60_600.yuv" "MINECRAFT_1080p" 1920 1080 600 60
-  run "MrFox_BlueBird_1920x1080_30.yuv" "MrFox_BlueBird_1080p" 1920 1080 300 30
-  run "Sintel_trailer_o537n480_1920x1080_24.yuv" "Sintel_trailer_1080p" 1920 1080 480 24
-  run "WITCHER3_1920x1080_60.yuv" "WITCHER3_1080p" 1920 1080 600 60
-
-  # Average BD-rates...
+if [[ -d "$file" ||
+  "$is_yuv" = "yes" &&
+  "$(can_process_yuv $width $height $framerate)" = "no" &&
+  "$(is_preset_stream ${file##*/})" = "yes" ]]; then
+  # run all preset streams
+  for i in {1..27}; do
+    stream=$(get_preset_stream $i)
+    [ "$nframes" -gt "0" ] && stream=$(echo $stream | sed s/'\w*$'/$nframes/)
+    run $stream
+  done
+  # average BD-rates...
   [[ "$skip_bdrate" = "no" ]] && compute_bdrate_averages
   exit $err
 fi
