demo: check for correct access permissions on user mapped folder
This change also removed -it option from docker run which is
dangerous for tests. Note https://github.com/docker/compose/issues/3623
which means that tty (-t) modifies standard output from the applications
running under docker and replace lf with crlf. As a result you might
have difficulties parsing docker output in tests.

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

diff --git a/assets/demo-bash b/assets/demo-bash
--- a/assets/demo-bash
+++ b/assets/demo-bash
@@ -4,7 +4,11 @@
 #  - /etc/demo.env contains environment variables needed to run a solution
 #  - demo-setup contains container runtime setup steps
 source /etc/demo.env
-demo-setup
+
+if ! demo-setup; then
+  echo "error: failed to setup demo" >&2
+  exit -1
+fi
 
 # Typical action performed by demo-setup is adding user(s) to some
 # groups to be able to access some resources, for example GPU.
